version: "3"
services:
  flask:
    depends_on: [redis]
    restart: always
    build: .
    ports:
     - "6300:9000"
    volumes:
     - ./app:/app
  redis:
    restart: always
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
     - /srv/data/quvide/geochecker/redis:/data
